# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  sdkVersion: '7.0.x'

steps:
- task: UseDotNet@2
  displayName: 'Install .Net Core 7.0 SDK'
  inputs:
    packageType: sdk
    version: $(sdkVersion)
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: 'Api/Api.csproj'
    arguments: '--configuration $(buildConfiguration) /p:Version=1.0.$(Build.BuildId) /p:AssemblyVersion=1.0.$(Build.BuildId) -o $(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'