name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t api .

    - name: Save Docker image to tar.gz
      run: docker save api | gzip > api.tar.gz

    - name: Copy tar.gz to remote server
      run: scp -i ${{ secrets.SERVER_SSH_KEY }} api.tar.gz root@${{ secrets.SERVER_IP }}:/root/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: SSH into the server and load Docker image
      uses: appleboy/ssh-action@v0.4.2
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        passphrase: ${{ secrets.SERVER_PASSPHRASE }}
        script: |
          docker load -i api.tar.gz
          docker run -d -p 5000:80 api
            
